### ISSUE TITLE
feature/view

### ISSUE THREAD

**Issue by lbowes** [lbowes/rcpsp-visualiser#16]
## Description
There should be an abstraction around the concept of a `View` of the model.

## TODO
- [x] Create a `View` class
- [x] Create an `update` method that takes in an instance of a `Model`
- [x] Create a `process` method that will take in a block of user input data (used to manipulate the view)
